### ISSUE TITLE
a cython implementation from autograd / GPy

### ISSUE THREAD

**Issue by mattjj** [imurray/chol-rev#1]
(This isn't really an issue with the code, just a pointer to some other code in case it's interesting. Feel free to close it immediately!)

We wrote a [Cholesky reverse-mode routine in autograd](https://github.com/HIPS/autograd/blob/542e2180961c6a5a7b19407d4e4c7de9f2e46ae7/autograd/numpy/linalg_extra.pyx) (and based it on one in [GPy](https://github.com/SheffieldML/GPy/blob/4be3bd33e0110b87c2fd9fd39abb331858a6c7df/GPy/util/choleskies_cython.pyx)). The code is in cython, which generates very nice C code and is a bit easier to build with Python, especially since it grabs BLAS function pointers from scipy at runtime and so doesn't have any other compile-time dependencies. I also wrote a loop instead of calling `dscal` because a modern C compiler can generate code at least as good as some level 1 routines.

I got a bit stuck on writing a routine for the second-order derivative. Smith 1995 doesn't seem to spell out a pure reverse-mode computation for the second derivative.

Your code here looks really nice, and being in Fortran it's not limited to just Python. Having a "LARMPACK" as you describe would indeed be awesome.

**Comment by imurray** [comment]
Thanks; I'm excited about autograd! Am I right in reading that it doesn't do level-3 BLAS blocking of anything? If so, I assume it will be quite a bit slower for large matrices. However, for a Python project, using cython seems a great idea. It would also be easy to port "my" code, from the Matlab or Fortran version. (I say "my" because it's the almost mechanical output of applying established math/algorithms to the LAPACK routines.)

The one thing you might have to do if going the cython route is replace ILAENV -- decide what a sensible block size is for the current architecture and problem size. I'm not sure you can get a function pointer for that LAPACK routine out of scipy.

I haven't looked at second derivatives yet. In principle I guess there's no problem, although whether it all works out neatly in-place in memory I don't know without trying.

**Comment by mattjj** [comment]
We didn't think about blocking, and I wasn't even aware of that technique until reading your code, so it's something I'm just learning about now :) Thanks for the pointer!

Generally speaking autograd can produce Python code for higher-order derivatives automatically, but in the particular case of [our current Cholesky grad implementation in Python](https://github.com/HIPS/autograd/blob/4152b58974e0358bfd5a675dcd8b5ddda11b77f0/autograd/numpy/linalg.py#L83-L102) the code uses assignment into arrays and so can't itself be autodiffed with autograd. Someday we'll rewrite it without assignment so we can generate higher-order derivatives. Smith 1995 does suggest there's a slick in-place or low-memory way to do it.

**Comment by mattjj** [comment]
Looks like [ILAENV is indeed excluded](https://github.com/scipy/scipy/blob/f378498102d1a5113eb3906606ede0de498e5ea8/scipy/linalg/_cython_signature_generator.py#L110-L128) from the scipy cython blas.

**Comment by imurray** [comment]
The blocked Cholesky (and its inverse) are much faster than the unblocked version — 50x faster for large matrices is typical on my laptop. I think it's ok to do some hand-crafting for a set of well-defined primitives that are going to be used a lot.
