### ISSUE TITLE
Small fixes for Matlab 2019b, Intel XE 2020 and Win 10

### ISSUE THREAD

**Issue by qwer1304** [imurray/chol-rev#2]
Hi,
Awsome code!
For the environment in the title, I had to do two small changes to make the system compile:

1. In chol_rev.c line 23, changed int64_t to long long. (I guess int64_t isn't included in stdint.h.)
2. In chol_rev.c line 30, changed  dpofrt to DPOFRT. (I guess the linker is case-sensitive.)

Cheers,
David

**Comment by imurray** [comment]
Thanks! I don't have a Windows machine to test on. You can see that I attempted to cover Windows with some #ifdefs, but clearly failed.

If you can tweak the #ifdefs so that it works on your machine, and still works on linux (which I can verify), I'd love to get a pull request. If fiddling with git/github is not your thing, you can also just attach a replacement file, and I'll sort it out (eventually).

(Optional: if you can test on Octave for Windows as well that would be awesome. I also have no idea if it builds on Matlab/Octave for Mac...)

**Comment by qwer1304** [comment]
Hi Ian,
That's the file I'm using now (attaching as zip as C files aren't allowed).
[chol_rev.zip](https://github.com/imurray/chol-rev/files/4701626/chol_rev.zip)

Actually, it's a slighly better fix: turns out that in this environment  \_\_STDC_VERSION\_\_ is NOT bigger than  199901L, but \_WIN32 is defined AND LONGLONG is NOT defined. So, replace LONGLONG with long long and you're good.

The second fix is with capitalization of DPOFRT.

Don't have Octave and my Linux environment isn't set to do proper testing.

**Comment by imurray** [comment]
Thanks! Should be fixed now. As both branches of an #ifdef now said "long long", I also removed that ifdef. Commit d85b1e3
